# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UILayoutSnapKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UILayoutSnapKit
pod 'SnapKit'
pod 'R.swift'

end
